// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mtxisdavxslgbefypvat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10eGlzZGF2eHNsZ2JlZnlwdmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MzMwODcsImV4cCI6MjA2NzIwOTA4N30.RWLj2tL0YdbI3pDcQ8zanK3aaQDSHbcmvSf5j16-DEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);